title: Patrick Merlot
tagline: "En essayant continuellement on finit par reussir. Donc plus ca rate, plus on a de chance que ca marche (Devise Shadok)."
owner: Patrick Merlot
link: https://github.com/Patechoc/
copyright: Copyright Patrick Merlot


pygments: true
permalink: '/:title'
markdown: kramdown

exclude: [README.md]
