# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patrick Merlot
email: patrick.merlot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I want to help liberate data on cities, countries, public health, inequalities to empower people and improve governance.
  Proud dad, computational scientist and engineer in electronics, I enjoy programming... anything!
  I believe in happiness at work and I am just looking for a place where I can improve
  and share my skills among great colleagues, work on mind blowing projects. And I love coffee!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Patechoc
github_username:  Patechoc

# Build settings
markdown: kramdown
