title: Patrick Merlot
tagline: "En essayant continuellement on finit par réussir. Donc : plus ça rate, plus on a de chance que ça marche." (Devise Shadok)
owner: Patrick Merlot
link: https://github.com/Patechoc/
copyright: Copyright Patrick Merlot


pygments: true
permalink: '/:title'
markdown: kramdown

exclude: [README.md]

